//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Domain.FxAggregate.Mapping
{
    #pragma warning disable 1573
    using System.Data.Entity.ModelConfiguration;
    using Fx.Entity.FxAggregate;
    
    internal partial class TopShows_Mapping : EntityTypeConfiguration<TopShow>
    {
        public TopShows_Mapping()
        {                        
              this.HasKey(t => t.TopShowId);
              this.ToTable("TopShow", "Aggregate");
              this.Property(t => t.TopShowId).HasColumnName("TopShowId");
              this.Property(t => t.ChannelCatagroy).HasColumnName("ChannelCatagroy");
              this.Property(t => t.InfoId).HasColumnName("InfoId");
              this.Property(t => t.Title).HasColumnName("Title").HasMaxLength(128);
              this.Property(t => t.HeadPicture).HasColumnName("HeadPicture").HasMaxLength(128);
              this.Property(t => t.Price).HasColumnName("Price");
         }
    }
}

