drop table dbo.aspnet_Membership
drop table dbo.aspnet_Profile
drop table dbo.aspnet_WebEvent_Events
drop table dbo.aspnet_SchemaVersions
drop table dbo.aspnet_PersonalizationPerUser
drop table dbo.aspnet_Paths
drop table dbo.UsersInRoles
drop table dbo.aspnet_Users
drop table dbo.aspnet_Roles
drop table dbo.aspnet_Applications
drop table dbo.ELMAH_Error