using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Fx.Entity.Catagroy
{
    public enum ChannelListDetailCatagroy
    {
        Phone = 1,
        Computer = 2,
        DigitalCamera = 3,
        ComputerAccessories = 4,
        PlayStations = 5,
        PSAccessories = 6,
        PhoneAccessories = 7,
        ElectronicsOther = 8,
        Furniture = 9,
        KitchenAppliances = 10,
        AudioAppliances = 11,
        KitchenDinningWares = 12,
        Decoration = 13,
        OtherElectronics = 14,
        GymEquipment = 15,
        Bike = 16,
        HomeSuppliesOther = 17,
        Clothing = 18,
        Shoes = 19,
        Bag = 20,
        Accessories = 21,
        FashionOther = 22,
        MusicInstruments = 23,
        Books = 24,
        Toys = 25,
        Stationary = 26,
        CultureLifeOther = 27,
        OtherOther = 28,
        Audi = 29,
        BMW = 30,
        Buick = 31,
        Citroen = 32,
        Ford = 33,
        Honda = 34,
        Toyota = 35,
        Nissan = 36,
        MINI = 37,
        MercedesBenz = 38,
        Peugeot = 39,
        VW = 40,
        Volvo = 41,
        SecondHandCarOther = 42,
        Shop = 43,
        Restaurants = 44,
        Warehouse = 45,
        Office = 46,
        House = 47,
        Flat = 48,
        StudentAparment = 49,
    }
}
