//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1573
namespace Fx.Domain.FxSite
{
    using System;
    using System.Data.Entity;
    using Fx.Domain.Account.Mapping;
    using Fx.Domain.FxSite.Mapping;
    using Fx.Entity.FxSite; 

    public class FxSiteContext : DbContext
    {
        static FxSiteContext()
        {
            //System.Data.Entity.Database.SetInitializer(new FxSiteInitializer());
        }

        public FxSiteContext()
            : base()
        {
            throw new NotImplementedException("因Hosting的变化，只有一个数据库，所以请勿使用");
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.Add(new ELMAH_Error_Mapping());
        }

        public DbSet<ELMAH_Error> ELMAHErrors { get; set; }

        public DbSet<Area> Areas { get; set; }

        public DbSet<City> Citys { get; set; }
    }
}
