//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Domain.FxSite.Mapping
{
#pragma warning disable 1573
    using System.Data.Entity.ModelConfiguration;
    using Fx.Entity.FxSite;

    internal partial class ChannelList_Mapping : EntityTypeConfiguration<ChannelList>
    {
        public ChannelList_Mapping()
        {
            this.HasKey(t => t.ChannelListId);
            this.ToTable("ChannelList", "Site");
            this.Property(t => t.ChannelListId).HasColumnName("ChannelListId");
            this.Property(t => t.ChannelListName).HasColumnName("ChannelListName").HasMaxLength(20);
            this.Property(t => t.Description).HasColumnName("Description").HasMaxLength(256);
            this.HasMany(r => r.ChannelListDetails).WithRequired();
        }
    }
}
