//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Domain.FxSite.Mapping
{
    #pragma warning disable 1573
    using System.Data.Entity.ModelConfiguration;
    using Fx.Entity.FxSite;
    
    internal partial class City_Mapping : EntityTypeConfiguration<City>
    {
        public City_Mapping()
        {                        
              this.HasKey(t => t.CityId);        
              this.ToTable("City","Site");
              this.Property(t => t.CityId).HasColumnName("CityId");
              this.Property(t => t.CityName).HasColumnName("CityName").IsRequired().HasMaxLength(50);
              this.Property(t => t.Sorted).HasColumnName("Sorted");
              this.Property(t => t.AreaID).HasColumnName("AreaID");
         }
    }
}
