//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Domain.FxSite.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
  
    
    internal partial class ELMAH_Error_Mapping : EntityTypeConfiguration<Fx.Entity.FxSite.ELMAH_Error>
    {
        public ELMAH_Error_Mapping()
        {                        
              this.HasKey(t => t.ErrorId);        
              this.ToTable("ELMAH_Error");
              this.Property(t => t.ErrorId).HasColumnName("ErrorId");
              this.Property(t => t.Application).HasColumnName("Application").IsRequired().HasMaxLength(60);
              this.Property(t => t.Host).HasColumnName("Host").IsRequired().HasMaxLength(50);
              this.Property(t => t.Type).HasColumnName("Type").IsRequired().HasMaxLength(100);
              this.Property(t => t.Source).HasColumnName("Source").IsRequired().HasMaxLength(60);
              this.Property(t => t.Message).HasColumnName("Message").IsRequired().HasMaxLength(500);
              this.Property(t => t.User).HasColumnName("User").IsRequired().HasMaxLength(50);
              this.Property(t => t.StatusCode).HasColumnName("StatusCode");
              this.Property(t => t.TimeUtc).HasColumnName("TimeUtc");
             // this.Property(t => t.Sequence).HasColumnName("Sequence").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.Identity));
              this.Property(t => t.Sequence).HasColumnName("Sequence");  
            this.Property(t => t.AllXml).HasColumnName("AllXml").IsRequired();
         }
    }
}

