//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Domain.Account.Mapping
{
    #pragma warning disable 1573
    using System.Data.Entity.ModelConfiguration;
    using Fx.Entity.MemberShip;
    
    internal partial class Applications_Mapping : EntityTypeConfiguration<Applications>
    {
        public Applications_Mapping()
        {                        
              this.HasKey(t => t.ApplicationId);
              this.ToTable("aspnet_Applications");
              this.Property(t => t.ApplicationName).HasColumnName("ApplicationName").IsRequired().HasMaxLength(256);
              this.Property(t => t.LoweredApplicationName).HasColumnName("LoweredApplicationName").IsRequired().HasMaxLength(256);
              this.Property(t => t.ApplicationId).HasColumnName("ApplicationId");
              this.Property(t => t.Description).HasColumnName("Description").HasMaxLength(256);
         }
    }
}
