//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Domain.Account.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Fx.Entity;
    
    internal partial class Paths_Mapping : EntityTypeConfiguration<Paths>
    {
        public Paths_Mapping()
        {                        
              this.HasKey(t => t.PathId);        
              this.ToTable("Paths");
              this.Property(t => t.ApplicationId).HasColumnName("ApplicationId");
              this.Property(t => t.PathId).HasColumnName("PathId");
              this.Property(t => t.Path).HasColumnName("Path").IsRequired().HasMaxLength(256);
              this.Property(t => t.LoweredPath).HasColumnName("LoweredPath").IsRequired().HasMaxLength(256);
              this.HasRequired(t => t.Applications).WithMany(t => t.Paths).HasForeignKey(d => d.ApplicationId);
         }
    }
}
