//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Domain.Account.Mapping
{
    #pragma warning disable 1573
    using System.Data.Entity.ModelConfiguration;
    using Fx.Entity.MemberShip;
    
    internal partial class PersonalizationAllUsers_Mapping : EntityTypeConfiguration<PersonalizationAllUsers>
    {
        public PersonalizationAllUsers_Mapping()
        {                        
              this.HasKey(t => t.PathId);
              this.ToTable("aspnet_PersonalizationAllUsers");
              this.Property(t => t.PathId).HasColumnName("PathId");
              this.Property(t => t.PageSettings).HasColumnName("PageSettings").IsRequired();
              this.Property(t => t.LastUpdatedDate).HasColumnName("LastUpdatedDate");
              this.HasRequired(t => t.Paths).WithOptional(t => t.PersonalizationAllUsers);
         }
    }
}
