//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Domain.Account.Mapping
{
    #pragma warning disable 1573
    using System.Data.Entity.ModelConfiguration;
    using Fx.Entity.MemberShip;
    
    internal partial class PersonalizationPerUser_Mapping : EntityTypeConfiguration<PersonalizationPerUser>
    {
        public PersonalizationPerUser_Mapping()
        {                        
              this.HasKey(t => t.Id);
              this.ToTable("aspnet_PersonalizationPerUser");
              this.Property(t => t.Id).HasColumnName("Id");
              this.Property(t => t.PathId).HasColumnName("PathId");
              this.Property(t => t.UserId).HasColumnName("UserId");
              this.Property(t => t.PageSettings).HasColumnName("PageSettings").IsRequired();
              this.Property(t => t.LastUpdatedDate).HasColumnName("LastUpdatedDate");
              this.HasOptional(t => t.Paths).WithMany(t => t.PersonalizationPerUser).HasForeignKey(d => d.PathId);
              this.HasOptional(t => t.Users).WithMany(t => t.PersonalizationPerUser).HasForeignKey(d => d.UserId);
         }
    }
}
