//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Domain.Account.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Fx.Entity;
    
    internal partial class Profile_Mapping : EntityTypeConfiguration<Profile>
    {
        public Profile_Mapping()
        {                        
              this.HasKey(t => t.UserId);        
              this.ToTable("Profile");
              this.Property(t => t.UserId).HasColumnName("UserId");
              this.Property(t => t.PropertyNames).HasColumnName("PropertyNames").IsRequired();
              this.Property(t => t.PropertyValuesString).HasColumnName("PropertyValuesString").IsRequired();
              this.Property(t => t.PropertyValuesBinary).HasColumnName("PropertyValuesBinary").IsRequired();
              this.Property(t => t.LastUpdatedDate).HasColumnName("LastUpdatedDate");
              this.HasRequired(t => t.Users).WithOptional(t => t.Profile);
         }
    }
}
