//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Domain.Account.Mapping
{
    #pragma warning disable 1573
    using System.Data.Entity.ModelConfiguration;
    using Fx.Entity.MemberShip;
    
    internal partial class WebEvent_Events_Mapping : EntityTypeConfiguration<WebEvent_Events>
    {
        public WebEvent_Events_Mapping()
        {                        
              this.HasKey(t => t.EventId);
              this.ToTable("aspnet_WebEvent_Events");
              this.Property(t => t.EventId).HasColumnName("EventId").IsRequired().IsUnicode(false).IsFixedLength().HasMaxLength(32);
              this.Property(t => t.EventTimeUtc).HasColumnName("EventTimeUtc");
              this.Property(t => t.EventTime).HasColumnName("EventTime");
              this.Property(t => t.EventType).HasColumnName("EventType").IsRequired().HasMaxLength(256);
              this.Property(t => t.EventSequence).HasColumnName("EventSequence");
              this.Property(t => t.EventOccurrence).HasColumnName("EventOccurrence");
              this.Property(t => t.EventCode).HasColumnName("EventCode");
              this.Property(t => t.EventDetailCode).HasColumnName("EventDetailCode");
              this.Property(t => t.Message).HasColumnName("Message").HasMaxLength(1024);
              this.Property(t => t.ApplicationPath).HasColumnName("ApplicationPath").HasMaxLength(256);
              this.Property(t => t.ApplicationVirtualPath).HasColumnName("ApplicationVirtualPath").HasMaxLength(256);
              this.Property(t => t.MachineName).HasColumnName("MachineName").IsRequired().HasMaxLength(256);
              this.Property(t => t.RequestUrl).HasColumnName("RequestUrl").HasMaxLength(1024);
              this.Property(t => t.ExceptionType).HasColumnName("ExceptionType").HasMaxLength(256);
              this.Property(t => t.Details).HasColumnName("Details");
         }
    }
}

