//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Domain.FxCar.Mapping
{
    #pragma warning disable 1573
    using System.Data.Entity.ModelConfiguration;
    using Fx.Entity.FxCar;
    
    internal partial class CarTransferInfo_Mapping : EntityTypeConfiguration<CarTransferInfo>
    {
        public CarTransferInfo_Mapping()
        {                        
              this.HasKey(t => t.CarTransferInfoId);        
              this.ToTable("CarTransferInfo","Car");
              this.Property(t => t.CarTransferInfoId).HasColumnName("CarTransferInfoId");
              this.Property(t => t.PublishTitle).HasColumnName("PublishTitle");
              this.Property(t => t.CatagroyId).HasColumnName("CatagroyId");
              this.Property(t => t.Price).HasColumnName("Price");
              this.Property(t => t.AreaId).HasColumnName("AreaId");
              this.Property(t => t.CityId).HasColumnName("CityId");
              this.Property(t => t.CarYear).HasColumnName("CarYear");
              this.Property(t => t.CarMileage).HasColumnName("CarMileage");
              this.Property(t => t.PublishUserEmail).HasColumnName("PublishUserEmail");
              this.Property(t => t.Mark).HasColumnName("Mark");
              this.Property(t => t.Controller).HasColumnName("Controller");
              this.Property(t => t.Action).HasColumnName("Action");
              this.Property(t => t.UserAccount).HasColumnName("UserAccount");
              this.Property(t => t.CreatedTime).HasColumnName("CreatedTime");
              this.Property(t => t.IsDelete).HasColumnName("IsDelete");
              this.Property(t => t.IsPublish).HasColumnName("IsPublish");
         }
    }
}
