//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Domain.FxCar.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Fx.Entity.FxCar;
    
    internal partial class CarTransferLogs_Mapping : EntityTypeConfiguration<CarTransferLog>
    {
        public CarTransferLogs_Mapping()
        {                        
              this.HasKey(t => t.CarTransferLogId);        
              this.ToTable("CarTransferLog","Car");
              this.Property(t => t.CarTransferLogId).HasColumnName("CarTransferLogId");
              this.Property(t => t.OperteName).HasColumnName("OperteName").HasMaxLength(32);
              this.Property(t => t.Source).HasColumnName("Source").HasMaxLength(32);
              this.Property(t => t.OperteTime).HasColumnName("OperteTime");
         }
    }
}
