//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Domain.FxHouse.Mapping
{
    #pragma warning disable 1573
    using System.Data.Entity.ModelConfiguration;
    using Fx.Entity.FxHouse;
    
    internal partial class HouseBuyLogs_Mapping : EntityTypeConfiguration<HouseBuyLog>
    {
        public HouseBuyLogs_Mapping()
        {                        
              this.HasKey(t => t.HouseBuyLogId);        
              this.ToTable("HouseBuyLog","House");
              this.Property(t => t.HouseBuyLogId).HasColumnName("HouseBuyLogId");
              this.Property(t => t.OperteName).HasColumnName("OperteName").HasMaxLength(32);
              this.Property(t => t.Source).HasColumnName("Source").HasMaxLength(32);
              this.Property(t => t.OperteTime).HasColumnName("OperteTime");
         }
    }
}
