//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Domain.FxHouse.Mapping
{
    #pragma warning disable 1573
    using System.Data.Entity.ModelConfiguration;
    using Fx.Entity;
    
    internal partial class PictureCdnErrors_Mapping : EntityTypeConfiguration<PictureCdnError>
    {
        public PictureCdnErrors_Mapping()
        {                        
              this.HasKey(t => t.PictureCdnErrorId);        
              this.ToTable("PictureCdnError","House");
              this.Property(t => t.PictureCdnErrorId).HasColumnName("PictureCdnErrorId");
              this.Property(t => t.ErorMsg).HasColumnName("ErorMsg").HasMaxLength(256);
              this.Property(t => t.ObjectId).HasColumnName("ObjectId");
              this.Property(t => t.SourceType).HasColumnName("SourceType");
         }
    }
}
