//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Entity.MemberShip
{
    
    using System;
    using System.Collections.Generic;
    
    public partial class Paths
    {
        public Paths()
        {
            this.PersonalizationPerUser = new HashSet<PersonalizationPerUser>();
        }
    
        public System.Guid ApplicationId { get; set; }
        public System.Guid PathId { get; set; }
        public string Path { get; set; }
        public string LoweredPath { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual PersonalizationAllUsers PersonalizationAllUsers { get; set; }
        public virtual ICollection<PersonalizationPerUser> PersonalizationPerUser { get; set; }
    }
}
