//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Entity
{
    
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.PersonalizationPerUser = new HashSet<PersonalizationPerUser>();
            this.Roles = new HashSet<Roles>();
        }
    
        public System.Guid ApplicationId { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string LoweredUserName { get; set; }
        public string MobileAlias { get; set; }
        public bool IsAnonymous { get; set; }
        public System.DateTime LastActivityDate { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual Membership Membership { get; set; }
        public virtual ICollection<PersonalizationPerUser> PersonalizationPerUser { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
