//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Domain.FxGoods.Mapping
{
#pragma warning disable 1573
    using System.Data.Entity.ModelConfiguration;
    using Fx.Entity;

    internal partial class BuyPicture_Mapping : EntityTypeConfiguration<BuyPicture>
    {
        public BuyPicture_Mapping()
        {
            this.HasKey(t => t.BuyPictureId);
            this.ToTable("BuyPicture","Goods");
            this.Property(t => t.BuyPictureId).HasColumnName("BuyPictureId");
            this.Property(t => t.BuyPictureCatagroy).HasColumnName("BuyPictureCatagroy");
            this.Property(t => t.PhysicalPath).HasColumnName("PhysicalPath").HasMaxLength(128);
            this.Property(t => t.ImageUrl).HasColumnName("ImageUrl").HasMaxLength(128);
            this.Property(t => t.IsCdn).HasColumnName("IsCdn");
            this.Property(t => t.CdnUrl).HasColumnName("CdnUrl").HasMaxLength(128);
        }
    }
}
