//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FxDomain.FxGoods.Mapping
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using Fx.Entity.FxGoods;

    internal partial class GoodsTransferInfo_Mapping : EntityTypeConfiguration<GoodsTransferInfo>
    {
        public GoodsTransferInfo_Mapping()
        {					
    		this.HasKey(t => t.GoodsTransferInfoId);
            this.ToTable("GoodsTransferInfo", "Goods");
            this.Property(t => t.GoodsTransferInfoId).HasColumnName("GoodsTransferInfoId");
    		this.Property(t => t.PublishUserEmail).HasColumnName("PublishUserEmail").HasMaxLength(128).HasColumnType("varchar");
            this.Property(t => t.PublishTitle).HasColumnName("PublishTitle").HasMaxLength(128).HasColumnType("varchar");
    		this.Property(t => t.Price).HasColumnName("Price");
            this.Property(t => t.Mark).HasColumnName("Mark").HasMaxLength(128).HasColumnType("varchar");
    		this.Property(t => t.CreatedTime).HasColumnName("CreatedTime");
    	}
    }
}

